#!/usr/bin/env bash
# Sets up nginx server with default configurations and custom response header
sudo apt-get update
sudo apt-get install nginx -y

#Hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Redirection to website
sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
#custom 404 erroe page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
#nginx uses custom 404 and  
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo sed -i '0,/try_files $uri $uri\/ =404;/!b;//i\\t\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo systemctl restart nginx 
