#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By

sudo apt-get update
sudo apt-get install nginx -y
#hello world file
echo "Hello World!" | sudo tee /var/www/html/index.html
#redirection created
sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
#custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
#configured nginx to 404
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo sed -i '0,/try_files $uri $uri\/ =404;/!b;//i\\t\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
#restarting server
sudo systemctl restart nginx 
