#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y

#hello page world
echo "Hello World!" | sudo tee /var/www/html/index.html

#redirection of website
sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
#custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html


sudo systemctl nginx restart

