#!/usr/bin/env bash

# This script installs HAproxy and configures it to send traffic to web-01 and web-02 using a roundrobin algorithm.

# Set the path of the HAproxy configuration file.
CONF="/etc/haproxy/haproxy.cfg"

sudo apt update
sudo apt install haproxy -y

# Enables HAproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start

# Configure HAproxy if the 'frontend client' section doesn't exist.
if ! grep -qF "frontend client" "$CONF"
then
    sudo tee -a "$CONF" <<EOF
frontend client
    bind *:80
    mode http
    default_backend myservers

backend myservers
    mode http
    server 134081-web-01 52.87.153.8:80 check
    server 134081-web-02 100.25.38.116:80 check
EOF
fi

# Restart HAproxy to apply the changes.
sudo service haproxy restart

