#!/usr/bin/env bash
# Install and configure HAproxy in my loadbalancer server

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfrontend
        bind *:8080
        default_backend myservers
backend myservers
        balance roundrobin
        server web-01 34.207.253.223:80 check
        server web-02 100.25.135.33:80 check
EOT

# start the loadbalancer
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
