#!/usr/bin/env bash
# This script replaces port 8080 in the Nginx configuration file with port 80.
#and starts the Nginx service.

sudo rm /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart 
