#!/usr/bin/env bash
# This script replaces port 8080 in the Nginx configuration file with port 80 and starts the Ngin# x service.

sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
