#!/usr/bin/env bash
#Displays the visitor IP along with the HTTP status code sorted
#The exact format must be:
#OCCURENCE_NUMBER IP HTTP_CODE
#In list format
awk '{ print $1, $9}' apache-access.log | sort | uniq -c | sort -rn
