#!/usr/bin/env bash

#stoping processes apache and nginx
sudo service nginx stop
sudo pkill apache2

sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t
#start nginx
sudo service nginx start
